FROM rdse/base

ARG JAR_NAME
ARG MASTER_HOST

ENV ROLE="master"
ENV HOST=$MASTER_HOST
ENV JAR_NAME=$JAR_NAME
ENV WORKERS=0
ENV MASTER_PORT=7877
ENV PATH_DATASET="data/data.csv"
ENV PATH_DATASET_GOLD="data/data_gold.csv"

EXPOSE $MASTER_PORT

CMD java -jar $JAR_NAME $ROLE \
        -w $WORKERS \
        -h $HOST \
        -p $MASTER_PORT \
        -d $PATH_DATASET \
        -g $PATH_DATASET_GOLD > $LOG_DIR/${LOG_SUB_DIR}${ROLE}.log && \ 
        touch $LOG_DIR/${LOG_SUB_DIR}${ROLE}.done.log
