FROM rdse/base

ARG JAR_NAME
ARG MASTER_HOST

ENV ROLE="master"
ENV HOST=$MASTER_HOST
ENV JAR_NAME=$JAR_NAME
ENV WORKERS=0
ENV MASTER_PORT=7877
ENV PATH_DATA="data/restaurant.csv"
ENV PATH_GOLD_STANDARD="data/restaurant_gold.csv"
ENV LOG_FILE="log/${ROLE}.log"

EXPOSE $MASTER_PORT

CMD java -jar $JAR_NAME $ROLE \
        -w $WORKERS \
        -h $HOST \
        -p $MASTER_PORT \
        -d $PATH_DATA \
        -g $PATH_GOLD_STANDARD > $LOG_FILE
